services:
  - type: web
    name: consulat-congo
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn consulat_site.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: ".onrender.com" 